name: Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Login to Firebase
        run: |
          echo "$FIREBASE_TOKEN" | firebase login --no-localhost

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

        working-directory: ./frontend
