name: Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: cd frontend

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --token "$FIREBASE_TOKEN"
